### ISSUE TITLE
1차 프로젝트 운영 방안

### ISSUE THREAD

**Issue by cocahack** [f-lab-edu/fream#38]
#### 배포

- 애플리케이션의 빌드 결과물은 무엇인가?
- 웹 서버, 애플리케이션, 그리고 데이터베이스는 어디에 어떻게 배포할 것인가?
- 다중화를 할 것인가?
- 무중단 배포를 할 것인가?
- CD는 어떻게 할 것인가?
    - 배포 실패 시 롤백은 어떻게 할 것인가?
        - 애플리케이션, 데이터베이스 스키마 롤백 전략

#### 운영

- 로그
    - 어떤 내용을 기록할 것인가? (Log level)
    - 어디에 저장할 것인가?
    - 기록된 로그를 어떻게 조회할 것인가?  
- 장애
    - 감지한 장애는 어떻게 통지를 받을 것인가?

---

#### TODO list
- [x] CI/CD 환경 구성
    - [x] Jenkins 구성
    - [x] 로컬 이미지 레지스트리 구성
    - [x] CI/CD 스크립트 작성
      - [x] Github Actions CI 를 Jenkins 로 이전
      - [x] main 브랜치 CI/CD 파이프라인 작성
    - [x] 무중단 배포

**Comment by cocahack** [comment]
@HyundeokPark 

일단 생각나는대로 적어봤습니다. 그 밖에 논의가 필요한 사항이 있다면 코멘트 주세요. 구체적인 내용은 모각코때 같이 논의하는걸로 해요.

---

CC. @f-lab-joseph

**Comment by cocahack** [comment]
#### 2021-12-10 논의 결과

- 컨테이너 사용
- 웹 서버, 앱, DB 등은 모두 단일 서버에 배포 (모두 컨테이너 사용)

**Comment by cocahack** [comment]
### TODO list

- [ ] CI/CD 환경 구성
  - [ ] Jenkins 구성
  - [ ] CI/CD 스크립트 작성
- [ ] 무중단 배포
