### ISSUE TITLE
v1 로컬 데모 환경 구성

### ISSUE THREAD

**Issue by cocahack** [f-lab-edu/fream#42]
### TODO list

- [x] 컨테이너 환경 구성
    - [x] 이미지 빌드 
    - [x] ~~docker-compose 배포~~ Docker CLI 만 사용하여 배포
- [ ] 앱 실행 
    - [x] seed data 추가
    - [ ] Postman collection 제공
